import "./globals.css";
import localFont from "next/font/local";

const transforma = localFont({
  src: "../public/fonts/TransformaMix_Trial-Regular.woff2",
});

export const metadata = {
  title: "Our Australia Tour",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={transforma.className}>{children}</body>
    </html>
  );
}
